version: "3.8"
services:
  jenkins:
    build: ./
    image: "joelee2012/standalone-jenkins:latest"
    ports:
      - "9090:8080"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    privileged: true
