name: Build Docker Image

on:
  push:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-image:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker tags
        id: get-docker-tag
        run: |
          version=$(curl -L https://www.jenkins.io/changelog-stable/rss.xml | grep '<title>Jenkins' | head -1 | grep -o [0-9.]*)
          echo "IMAGE_TAG=${version}-lts-alpine" >> $GITHUB_OUTPUT

      - name: Build docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            IMAGE_TAG=${{ steps.get-docker-tag.outputs.IMAGE_TAG }}
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-docker-tag.outputs.IMAGE_TAG }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.get-docker-tag.outputs.IMAGE_TAG }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Test docker image
        run: |
          docker images
          pip install -U pytest api4jenkins
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}:${{ steps.get-docker-tag.outputs.IMAGE_TAG }} pytest -v test_image.py

          #      - name: Push docker image
          #        uses: docker/build-push-action@v6
          #        id: push
          #        if: github.ref_name == 'main'
          #        with:
          #          context: .
          #          file: ./Dockerfile
          #          push: true
          #          build-args: |
          #            IMAGE_TAG=${{ steps.get-docker-tag.outputs.IMAGE_TAG }}
          #          tags: |
          #            ${{ github.repository }}:latest
          #            ${{ github.repository }}:${{ steps.get-docker-tag.outputs.IMAGE_TAG }}
          #            ghcr.io/${{ github.repository }}:latest
          #            ghcr.io/${{ github.repository }}:${{ steps.get-docker-tag.outputs.IMAGE_TAG }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
