name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Docker tags
        id: get-docker-tag
        run: echo "::set-output name=tag::$(sed -r '/FROM/!d;s/.*://g' Dockerfile)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-docker-tag.outputs.tag }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Test docker image
        run: |
          pip install -U pytest api4jenkins
          DOCKER_IMAGE=${{ github.repository }}:latest pytest -v tests/test_image.py

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-docker-tag.outputs.tag }}
