name: ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get Docker tags
        id: get-docker-tag
        run: |
          tag=$(sed -r '/FROM/!d;s/.*://g' Dockerfile)
          echo "IMAGE_TAG=$tag" >> $GITHUB_OUTPUT

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-docker-tag.outputs.IMAGE_TAG }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Test docker image
        run: |
          pip install -U pytest api4jenkins
          DOCKER_IMAGE=${{ github.repository }}:latest pytest -v test_image.py

      - name: Push docker image
        uses: docker/build-push-action@v3
        if: github.ref_name == 'main'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-docker-tag.outputs.IMAGE_TAG }}
